name: hdsemg-pipe
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.5
  - pyqt=5.15.*
  - requests>=2.26.0
  - torch>=1.10.0
  - hdsemg-shared>=0.10.7
  - h5py
  - pip
  - pip:
    - pyinstaller>=6.11.0