name: hdsemg-pipe
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.5
  - pyqt=5.15.*
  - h5py
  - pip
  - pip:
      - torch>=1.10.0
      - pyinstaller>=6.11.0
      - requests>=2.26.0