name: hdsemg-pipe
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.5
  - pyqt=5.15
  - requests>=2.26.0
  - cpuonly
  - pytorch>=1.10.0
  - hdsemg-shared>=0.11.1
  - hdsemg-select>=0.1.1
  - h5py
  - pip
  - pip:
      - pyqt5-tools>=5.15.9.3.3