name: hdsemg-preprocessing
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pyqt>=5.15           # satisfies PyQt5>=5.15
  - matplotlib>=3.4
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3
  - pytorch>=1.10        # "torch" on PyPI
  - requests>=2.26

  # make sure pip itself is present
  - pip

  # these get installed by pip inside the same env
  - pip:
    - hdsemg-pipe
    - pyqt5-tools>=5.15.9.3.3  # only available on PyPI
