site_name: hdsemg-pipe
repo_name: hdsemg-pipe
repo_url: https://github.com/johanneskasser/hdsemg-pipe
site_url: https://johanneskasser.github.io/hdsemg-pipe/
site_description: 'A Python application for cleaning and preparing high-density surface electromyography (HDsEMG) data.'
site_author: 'Johannes Kasser'

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  color_mode: dark
  user_color_mode_toggle: true

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Installation: installation.md
  - General Documentation:
      - Getting Started: general/getting_started.md
      - Dashboard: general/dashboard.md
      - Application Settings: general/application_settings.md
  - Processing Steps:
      - Opening Data: processing/opening_data.md
      - Grid Association: processing/grid_association.md
      - Crop to Region of Interest: processing/crop_to_roi.md
      - Cannel Selection: processing/channel_selection.md
      - Decomposition Results: processing/decomposition_results.md
  - Developer Guide: developer.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs/includes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [hdsemg_pipe]