name: Build and Release hdsemg-pipe

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
          pip install pyinstaller PyQt5
        shell: cmd

      - name: Compile resources file
        working-directory: ./src
        run: |
          if not exist resources_rc.py (
            echo Compiling resources.qrc to resources_rc.py
            pyrcc5 resources.qrc -o resources_rc.py
          ) else (
            echo resources_rc.py exists, skipping compilation
          )
        shell: cmd

      - name: Build executable
        working-directory: ./src
        run: |
          pyinstaller hdsemg-pipe.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hdsemg-pipe
          path: ./src/dist/hdsemg-pipe.exe

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/hdsemg-shared/
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.

      - name: Set package Version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        working-directory: ./src/shared_logic
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        working-directory: ./src/shared_logic
        run: twine upload dist/*
