name: Build and Release hdsemg-pipe

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
          pip install pyinstaller PyQt5
        shell: cmd
      - name: Compile resources file
        working-directory: ./src
        run: |
          if not exist resources_rc.py (
            echo Compiling resources.qrc to resources_rc.py
            pyrcc5 resources.qrc -o resources_rc.py
          ) else (
            echo resources_rc.py exists, skipping compilation
          )
        shell: cmd

      - name: Build executable
        working-directory: ./src
        run: |
          pyinstaller hdsemg-pipe.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hdsemg-pipe
          path: ./src/dist/hdsemg-pipe.exe

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src/dist/hdsemg-pipe.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
              This is a release for version ${{ github.ref_name }}.
              It contains the compiled executable for the hdsemg-pipe application.